### ISSUE TITLE
Ground Station Flight Dashboard Technical Spec Doucument

### ISSUE THREAD

**Issue by David-Rey** [VIP-LES/EosGround#20]
Talk about how the technical specs of the website such as the backend, data pipelines, etc.

**Comment by DarylDohner** [comment]
Prediction software aspect forked over to https://github.com/VIP-LES/EosGround/issues/21

**Comment by DarylDohner** [comment]
Ready for review: https://docs.google.com/document/d/1cx0xWhYR7gbwxyq0E980TPe3rSJgBJDHJk4HnmJ7oG0/edit#

**Comment by DarylDohner** [comment]
approved.  OpenMCT was selected
