### ISSUE TITLE
Prediction Software Tech Spec

### ISSUE THREAD

**Issue by DarylDohner** [VIP-LES/EosGround#21]

**Comment by IonLi09** [comment]
https://docs.google.com/document/d/1rl50wNVteM_YCgskGz9yTajigq_Ujw4oiQ433Tl5fgQ/edit?usp=sharing

**Comment by DarylDohner** [comment]
Can you please put this file in the software folder on the drive?
https://drive.google.com/drive/folders/1Jnu3agggzV9eFoCsKiyOqIemrK3e7W1A

Also, after group discussion we would like to implement this without using ML / AI as there won't be nearly enough training data

**Comment by IonLi09** [comment]
Moved and updated!

**Comment by DarylDohner** [comment]
looks good!  feel free to close
