### ISSUE TITLE
I like to solve the issues in the project and want to contribute 

### ISSUE THREAD

**Issue by apoorvthedude** [VIP-LES/EosGround#44]
Hello to every contributor,
I saw readme.me file & file structure of project and app.
But didn't understand what u folks want to make but looking something cool & exciting.

If u folks,brief me about your project.Then I can help u make this project & like to contribute to it.

**Comment by DarylDohner** [comment]
Hello,

Thank you for your interest.  The EosPlatform project developed by the Lightning from the Edge of Space Research Group at the Georgia Institute of Technology.  Currently we are not accepting new contributors.

Best,
The LES Team
